---
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- fail: msg="PACKAGE_LOCATION is required"
  when:
    - PACKAGE_LOCATION is not defined

- name: Include vars of all.yaml.
  include_vars:
    file: all.yaml
    name: all_vars

- name: Converting PACKAGE_LOCATION to absolute path
  shell: realpath {{ PACKAGE_LOCATION }}
  register: PACKAGE_LOCATION_ABSOLUTE

- name: Update and upgrade apt packages
  become: yes
  apt:
    update_cache: yes

- name: Install dependencies.
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - graphviz
      - debhelper
      - dh-autoreconf
      - python-all
      - python-twisted-conch
      - module-assistant
      - openssl
      - pkg-config
      - libssl-dev
      - build-essential
      - dkms
      - uuid-runtime

- name: Load built packages.
  shell: dpkg -i {{PACKAGE_LOCATION_ABSOLUTE.stdout}}/{{ item }}
  become: yes
  with_items:
    - "{{ all_vars.packages }}"

- name: Configuring private package manager.
  shell: echo "{{ all_vars.private_package }}" | tee /etc/apt/sources.list.d/{{ all_vars.source_name }}.list
  become: yes

- name: Add Apt signing key.
  shell: apt-key adv --fetch-keys "{{ all_vars.apt_key }}"
  become: yes

- name: Update and upgrade apt packages.
  become: yes
  apt:
    update_cache: yes

- name: Configuring magma apt preferences.
  shell: "{{ item }}"
  become: yes
  with_items:
    - 'echo "Package: *" > /etc/apt/preferences.d/magma-preferences'
    - 'echo "Pin: origin packages.magma.etagecom.io" >> /etc/apt/preferences.d/magma-preferences'
    - 'echo "Pin-Priority: 900" >> /etc/apt/preferences.d/magma-preferences'

- name: Installing magma.
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - 'magma={{ magma_version }}'

- name: Start service openvswitch-switch.
  become: yes
  service:
    name: openvswitch-switch
    state: started
  tags:
    - skipfirstinstall

# Ansible's service module doesn't support wildcards so we have to use shell
- name: Stop all magma services.
  become: yes
  shell: service magma@* stop
  tags:
    - skipfirstinstall

- name: Bring up gtp_br0
  shell: ifup gtp_br0
  become: yes
  tags:
    - skipfirstinstall

- name: Bring up mtr0
  shell: ifup mtr0
  become: yes
  tags:
    - skipfirstinstall

- name: Bring up uplink_br0
  shell: ifup uplink_br0
  become: yes
  tags:
    - skipfirstinstall

- name: Bring up ipfix0
  shell: ifup ipfix0
  become: yes
  tags:
    - skipfirstinstall

- name: Bring up dhcp0
  shell: ifup dhcp0
  become: yes
  tags:
    - skipfirstinstall

- name: Start service magma@magmad.
  become: yes
  service:
    name: magma@magmad
    state: started
  tags:
    - skipfirstinstall
